// Auto-generated by scripts/generate-static-data.ts
// Do not edit manually. Run: npx tsx scripts/generate-static-data.ts

export interface StoryCard {
  storyId: string;
  slug: string;
  title: string;
  summary: string;
  lifeStage: string;
  themes: string[];
  wordCount: number;
  principles: string[];
  volume?: string;
}

export interface ThemeCard {
  slug: string;
  name: string;
  storyCount: number;
  storyIds: string[];
}

export interface TimelineEvent {
  year: number;
  event: string;
  organization: string;
  location: string;
  storyRef: string;
  illustration?: string;
}

export const storiesData: StoryCard[] = [
  {
    "storyId": "P1_S01",
    "slug": "a-towhead-from-the-red-clay-hills",
    "title": "A Towhead from the Red Clay Hills",
    "summary": "A memoirist recalls growing up in Calhoun City, Mississippi in the 1940s–1950s, describing family lineage, small-town community life, and formative experiences that shaped his identity.",
    "lifeStage": "Childhood",
    "themes": [
      "Career Choices",
      "Community",
      "Gratitude",
      "Identity",
      "Work Ethic"
    ],
    "wordCount": 1317,
    "principles": [
      "Value community and hard work as central virtues.",
      "Early influences (home, school, church) are foundational to character development.",
      "Remembering origins helps explain later choices and identity.",
      "Hands-on community activities and local institutions provide practical learning opportunities."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S02",
    "slug": "a-v-ery-busy-teenager",
    "title": "A Very Busy Teenager",
    "summary": "A former high-school student recounts a busy four years filled with strong academics, extensive extracurricular involvement, health crises, and the choice of a college major influenced by an aptitude test.",
    "lifeStage": "Education",
    "themes": [
      "Adversity",
      "Career Choices",
      "Gratitude",
      "Identity",
      "Leadership",
      "Mentorship",
      "Work Ethic"
    ],
    "wordCount": 2456,
    "principles": [
      "High-quality teaching produces lasting advantage and prepares for future success.",
      "Extracurricular activities build skills, confidence, and social bonds.",
      "Leaders must develop delegation skills rather than assuming excessive responsibility.",
      "Adversity can be an opportunity to learn durable skills."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S02",
    "slug": "a-very-busy-teenager",
    "title": "A Very Busy Teenager",
    "summary": "A former high-school student recounts a busy four years filled with strong academics, extensive extracurricular involvement, health crises, and the choice of a college major influenced by an aptitude test.",
    "lifeStage": "Education",
    "themes": [
      "Adversity",
      "Career Choices",
      "Gratitude",
      "Identity",
      "Leadership",
      "Mentorship",
      "Work Ethic"
    ],
    "wordCount": 2456,
    "principles": [
      "High-quality teaching produces lasting advantage and prepares for future success.",
      "Extracurricular activities build skills, confidence, and social bonds.",
      "Leaders must develop delegation skills rather than assuming excessive responsibility.",
      "Adversity can be an opportunity to learn durable skills."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S03",
    "slug": "a-remarkable-teacher-s-legacy",
    "title": "A Remarkable Teacher’s Legacy",
    "summary": "A devoted, intellectually curious high-school English teacher in a rural community demanded rigorous standards and memorization, profoundly shaping students' lives and inspiring alumni to preserve her legacy.",
    "lifeStage": "Education",
    "themes": [
      "Career Choices",
      "Community",
      "Curiosity",
      "Gratitude",
      "Identity",
      "Mentorship",
      "Work Ethic"
    ],
    "wordCount": 970,
    "principles": [
      "High standards and disciplined practice produce lasting knowledge and character.",
      "Private, firm encouragement motivates improvement more effectively than public scolding.",
      "Consistent intellectual curiosity and exposure to literature expand students' horizons in limited-opportunity settings.",
      "Communities can preserve and extend a leader's legacy through collective action (memorials and scholarships)."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S04",
    "slug": "on-my-honor",
    "title": "On My Honor",
    "summary": "A personal memoir of Boy Scout experiences emphasizing mentorship, discipline, structured progression, charity, and the lasting influence of Scout values and leaders such as Dr. Carter Dobbs.",
    "lifeStage": "Childhood",
    "themes": [
      "Career Choices",
      "Curiosity",
      "Gratitude",
      "Identity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 2129,
    "principles": [
      "Leaders should model the behaviors they expect from others.",
      "Require genuine effort before granting rewards to instill discipline and competence.",
      "Consistent mentorship during formative years shapes long-term character and choices.",
      "Use structured milestones and visible recognition to motivate progress and learning.",
      "Embed charity and service as routine practices to reinforce citizenship."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S05",
    "slug": "a-would-be-music-man",
    "title": "A Would-be Music Man",
    "summary": "An individual with clear musical talent but limited discipline recounts childhood and high-school musical experiences, mentors, missed opportunities, and lifelong love of music despite not pursuing mastery.",
    "lifeStage": "Childhood",
    "themes": [
      "Adversity",
      "Career Choices",
      "Community",
      "Curiosity",
      "Financial Responsibility",
      "Gratitude",
      "Identity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 2116,
    "principles": [
      "Lifelong engagement can come from enjoyment even without technical mastery.",
      "Mentor demonstration and support can compensate for formal-skill gaps and create opportunities.",
      "Be honest with yourself about willingness to invest time; declining commitments may be preferable to half-hearted participation.",
      "Regret follows neglected natural gifts when discipline is lacking."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S06",
    "slug": "bayne-cobb-exemplar-of-a-dad",
    "title": "Bayne Cobb, Exemplar of a Dad",
    "summary": "A son reflects on his father's quiet, steady leadership across family, work, and adversity, highlighting lessons learned by observation over decades.",
    "lifeStage": "Childhood",
    "themes": [
      "Adversity",
      "Community",
      "Curiosity",
      "Financial Responsibility",
      "Identity",
      "Integrity",
      "Leadership",
      "Mentorship"
    ],
    "wordCount": 2843,
    "principles": [
      "Lead by example rather than by instruction.",
      "Maintain calm composure under stress; model steadiness.",
      "Prioritize financial responsibility and avoid debt.",
      "Respect and trust others; assume positive regard.",
      "Diligent work ethic and consistent service define leadership."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S07",
    "slug": "frances-cobb-a-spool-of-blue-thread",
    "title": "Frances Cobb—A Spool of Blue Thread",
    "summary": "A memoir sketch of Frances Cobb, a hardworking seamstress and mother whose ambition, exacting standards, and health struggles shaped her family's economic life and her children's upbringing.",
    "lifeStage": "Childhood",
    "themes": [
      "Adversity",
      "Career Choices",
      "Curiosity",
      "Integrity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 2474,
    "principles": [
      "Lead through industriousness and skill mastery to create economic opportunity.",
      "When constrained, pursue practical compromises rather than ideal solutions to make progress.",
      "Teach practical skills through hands-on instruction and close supervision to build competence.",
      "Maintain very high standards and enforce them consistently to instill discipline."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S08",
    "slug": "blue-and-ruby-cole",
    "title": "Blue and Ruby Cole",
    "summary": "Neighbors Blue and Ruby Cole acted as surrogate parents, offering time, protection, and practical help across decades; their long devotion culminated in Ruby leaving her estate to Sandy and Daddy, a surprising reward for years of care.",
    "lifeStage": "Childhood",
    "themes": [
      "Career Choices",
      "Community",
      "Family",
      "Financial Responsibility",
      "Gratitude",
      "Identity",
      "Work Ethic"
    ],
    "wordCount": 1546,
    "principles": [
      "Consistent generosity of time and small acts builds deep, lasting emotional bonds.",
      "Long-term devotion and caregiving can lead to unexpected tangible rewards.",
      "Protecting a child may justify shielding them from consequences, even by bending the truth.",
      "Small, everyday behaviors contribute to enduring legacies—both emotional and material."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S09",
    "slug": "a-work-ethic-develops",
    "title": "A Work Ethic Develops",
    "summary": "Narrator describes growing up with early assigned chores, family small-business work, and successive summer jobs that developed entrepreneurship, skills, and savings habits.",
    "lifeStage": "Childhood",
    "themes": [
      "Adversity",
      "Career Choices",
      "Curiosity",
      "Financial Responsibility",
      "Integrity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 2495,
    "principles": [
      "Instill work as a fundamental part of childhood development to build habits and responsibility.",
      "Hands-on tasks create skill, pride, and quality workmanship.",
      "Fairly share proceeds when others provide capital or resources.",
      "Maintain confidentiality in business matters.",
      "Trust and responsibility accelerate learning and leadership development."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S10",
    "slug": "roominations",
    "title": "Roominations",
    "summary": "A teenager describes how a small private bedroom, books, radio and music fostered curiosity and reflection, leading him to seize a university opportunity and leave his insular hometown.",
    "lifeStage": "Education",
    "themes": [
      "Career Choices",
      "Community",
      "Curiosity",
      "Gratitude",
      "Identity",
      "Work Ethic"
    ],
    "wordCount": 1762,
    "principles": [
      "Create a private physical space to enable reflection, identity formation, and concentrated learning.",
      "Sustained curiosity is a primary driver of learning and life-direction.",
      "Assemble and use information resources and media to access the wider world and expand perspective.",
      "When opportunity appears, act decisively rather than hesitating."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S11",
    "slug": "early-wanderlust",
    "title": "Early Wanderlust",
    "summary": "A narrator recounts formative travel experiences from childhood through college that sparked curiosity, personal growth, and a lifelong passion for exploring beyond a small hometown.",
    "lifeStage": "Education",
    "themes": [
      "Career Choices",
      "Community",
      "Curiosity",
      "Financial Responsibility",
      "Gratitude",
      "Identity",
      "Work Ethic"
    ],
    "wordCount": 2080,
    "principles": [
      "Curiosity and travel stimulate learning that cannot occur within a narrow local environment.",
      "Direct questioning and engagement accelerate understanding of unfamiliar subjects.",
      "Firsthand exposure to broader peers reveals true skill levels and drives improvement.",
      "Treat small losses or mistakes as lessons and adjust future behavior accordingly.",
      "Spontaneous, low-resource ventures can create lasting, formative memories."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S12",
    "slug": "by-the-light-of-the-silvery-moon",
    "title": "By the Light of the Silvery Moon",
    "summary": "A first-person account of two neighbors who moved from casual acquaintances in high school to lifelong partners, built on shared values, sustained communication during separations, and a deliberate engagement.",
    "lifeStage": "Education",
    "themes": [
      "Career Choices",
      "Community",
      "Curiosity",
      "Family",
      "Financial Responsibility",
      "Gratitude",
      "Identity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 1447,
    "principles": [
      "Shared core values are foundational for durable partnerships.",
      "Honesty, integrity, and work ethic are central selection criteria for a life partner.",
      "Consistent communication sustains relationships across distance.",
      "Deliberate saving and preparation enable committed steps despite financial constraints.",
      "Mutual support and aligned fundamental values reduce conflict and strengthen long-term bonds."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S13",
    "slug": "the-power-of-momentum",
    "title": "The Power of Momentum",
    "summary": "A student from a small town leverages early academic advantages to build momentum in college, helps teammates, confronts perceived unfairness, and makes pragmatic career choices aided by mentors.",
    "lifeStage": "Education",
    "themes": [
      "Career Choices",
      "Curiosity",
      "Financial Responsibility",
      "Integrity"
    ],
    "wordCount": 2810,
    "principles": [
      "Early wins create sustained momentum that fuels future success.",
      "Investigate and challenge actions that appear unfair rather than accepting them passively.",
      "Leverage mentor relationships; mentors can open opportunities and provide lasting support.",
      "Listening and understanding in the moment can substitute for exhaustive outside study.",
      "Accept practical compensations that address immediate needs and align incentives."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S14",
    "slug": "togetherness-on-saturday",
    "title": "Togetherness on Saturday",
    "summary": "A 1959 freshman is assigned to a notoriously strict, silent English professor and must decide whether to drop the required course or stay and figure out how to earn a passing grade; through pattern analysis and experimentation the student improves from an F to an A.",
    "lifeStage": "Education",
    "themes": [
      "Financial Responsibility",
      "Leadership"
    ],
    "wordCount": 1024,
    "principles": [
      "Treat difficult situations as laboratories for problem solving.",
      "Analyze patterns in outcomes and iteratively test solutions.",
      "Trust your intuition and sharpen the ability to think on your feet."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S15",
    "slug": "public-service-101",
    "title": "Public Service 101",
    "summary": "A college student's rise to Student Government Association president, accomplishments (election reform, campus campaigns), ethical lapses (press interference, celebratory arson), and a concluding resolve to avoid politics.",
    "lifeStage": "Education",
    "themes": [
      "Adversity",
      "Community",
      "Financial Responsibility",
      "Integrity",
      "Leadership"
    ],
    "wordCount": 2368,
    "principles": [
      "Diligent preparation builds credibility and influence.",
      "Implement transparent processes to address institutional unfairness.",
      "Stand against discrimination publicly, even when confronted by powerful figures.",
      "Power can lead to ethical compromise; self-awareness and corrective action matter.",
      "Accept reprimand and learn when mistakes endanger others or break rules."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S16",
    "slug": "launching-a-career",
    "title": "Launching a Career",
    "summary": "A graduating senior in late 1962 evaluates multiple job offers (Big Eight accounting firms, IBM, others), uses deliberate research and visits to choose Peat Marwick in Jackson, prioritizing cultural fit and long-term advancement over short-term pay.",
    "lifeStage": "Early Career",
    "themes": [
      "Career Choices",
      "Curiosity",
      "Leadership"
    ],
    "wordCount": 2061,
    "principles": [
      "Make a deliberate list of evaluation criteria before choosing.",
      "Consider both objective measures (reputation, size, advancement) and subjective fit (people, clients, culture).",
      "Prioritize long-term fit and advancement over short-term salary.",
      "Use in-person visits to assess organizations and people.",
      "Seek and weigh counsel from trusted advisors and family when making major career decisions."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S17",
    "slug": "chronology-of-a-career",
    "title": "Chronology of a Career",
    "summary": "A reflective chronology of a forty-plus-year business career emphasizing lifelong learning, mentorship, serendipity, and a fluid view of retirement.",
    "lifeStage": "Reflection",
    "themes": [
      "Career Choices",
      "Gratitude",
      "Identity",
      "Mentorship",
      "Work Ethic"
    ],
    "wordCount": 286,
    "principles": [
      "Practice gratitude and acknowledge others' contributions.",
      "Cultivate and value mentorship and tutelage.",
      "Treat career as a lifelong learning process to hone skills and shape character.",
      "Remain adaptable about phases of involvement, including retirement."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S18",
    "slug": "early-years-at-peat-marwick",
    "title": "Early Years at Peat Marwick",
    "summary": "A newly minted accountant joins Peat Marwick in 1963, rapidly advances through demanding audit work, assumes responsibility during crises, and becomes the firm's youngest partner by 1970.",
    "lifeStage": "Early Career",
    "themes": [
      "Career Choices",
      "Curiosity",
      "Gratitude",
      "Identity",
      "Integrity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 3749,
    "principles": [
      "Assume personal ownership of deliverables when accountability gaps appear.",
      "Cultivate and rely on mentors and sponsors to champion advancement.",
      "Seek technical expertise and formal review when operating at the edge of regulatory complexity.",
      "Embrace intense, challenging assignments as accelerants for learning and career momentum."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S19",
    "slug": "on-the-move-as-a-peat",
    "title": "On the Move as a Peat",
    "summary": "A newly made partner at Peat Marwick asserts ownership by pushing for the removal of a negligent partner and later accepts an invitation to establish a new office in Orlando after securing a visit with his wife.",
    "lifeStage": "Early Career",
    "themes": [
      "Career Choices",
      "Gratitude",
      "Identity",
      "Integrity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 825,
    "principles": [
      "Assume ownership and use formal authority to address previously suppressed problems.",
      "Raise concerns about professional negligence when it endangers clients and the firm.",
      "Leverage formal position to make previously withheld views known.",
      "Include family considerations in major relocation decisions."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S20",
    "slug": "the-florida-frontier",
    "title": "The Florida Frontier",
    "summary": "A young Peat Marwick partner relocates to Orlando in 1971 to establish a new office with little local research or resources, builds a small team and client base, then recommends closing the office when local market fundamentals prove weak.",
    "lifeStage": "Early Career",
    "themes": [
      "Adversity",
      "Career Choices",
      "Curiosity",
      "Gratitude",
      "Identity",
      "Integrity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 1956,
    "principles": [
      "Assess local market fundamentals before committing long-term resources.",
      "Be candid with leadership and present a documented, on-the-ground assessment even when recommendations are difficult.",
      "Build local networks and leverage introductions to generate early clients when starting from scratch.",
      "Start small and iterate: use temporary arrangements to establish presence before scaling.",
      "Accept responsibility for firm resources and act to prevent prolonged unprofitability."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S21",
    "slug": "new-roots-in-fort-lauderdale",
    "title": "New Roots in Fort Lauderdale",
    "summary": "A managing partner relocates to Fort Lauderdale (1975), builds a successful audit practice by recruiting talent and cultivating relationships, navigates major client work, fraud investigations, and a disruptive firm merger, then accepts a transfer to Baltimore in 1989.",
    "lifeStage": "Early Career",
    "themes": [
      "Adversity",
      "Community",
      "Curiosity",
      "Financial Responsibility",
      "Identity",
      "Leadership"
    ],
    "wordCount": 4030,
    "principles": [
      "Proactively seek counsel and ask questions to learn the local landscape.",
      "Invest personal resources—time and money—to build credibility and obtain leadership positions.",
      "Recruit and retain top talent as the foundation of a successful professional practice.",
      "When you don't understand a prospective client's business, decline the engagement to protect integrity.",
      "Act on ethical intuition promptly, even if it risks discomfort with peers."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S22",
    "slug": "kpmg-baltimore",
    "title": "KPMG—Baltimore",
    "summary": "An external managing partner is brought into an insular, stagnating KPMG Baltimore office (1989–1991), uses aggressive external networking and decisive personnel actions to reposition the office and broaden client relationships before being reassigned to Philadelphia.",
    "lifeStage": "Leadership",
    "themes": [
      "Curiosity",
      "Financial Responsibility",
      "Integrity",
      "Leadership"
    ],
    "wordCount": 2713,
    "principles": [
      "Aggressive, external networking produces tangible business and community results.",
      "Avoid groupthink and test internal assumptions against external reality.",
      "Engage clients at senior executive levels to protect and grow major relationships.",
      "Make difficult personnel decisions when objective performance and client needs demand it.",
      "Verify internal narratives by asking clients directly before changing operations tied to perceived image."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S23",
    "slug": "kpmg-philadelphia",
    "title": "KPMG—Philadelphia",
    "summary": "A KPMG leader arrives in Philadelphia (1991), confronts a resistant partner culture and weak client relationships, uses external assessment and direct relationship-building to turn the office around while managing firm-wide compensation reform and personal family health challenges.",
    "lifeStage": "Leadership",
    "themes": [
      "Career Choices",
      "Curiosity",
      "Financial Responsibility",
      "Gratitude",
      "Identity",
      "Work Ethic"
    ],
    "wordCount": 2521,
    "principles": [
      "Use independent, professional assessment to diagnose talent and culture when internal objectivity is compromised.",
      "Initiate relationships directly; don't let gatekeeping or protocol prevent access to senior client executives.",
      "Move decisively and rapidly when leading a turnaround; bold, timely action can accelerate change.",
      "Leverage civic and philanthropic engagement to build networks and open doors in a new community.",
      "Address systemic unfairness with iterative, data-driven redesigns to gain credible, implementable solutions."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S24",
    "slug": "kpmg-financial-services",
    "title": "KPMG Financial Services",
    "summary": "Keith Cobb was appointed to lead KPMG's newly reorganized Financial Services unit, faced partner skepticism due to his non-specialist background, mounted a highly prepared, consultant-backed presentation at a national meeting to establish credibility and drive adoption of a five-point strategy, and later accepted an external CEO offer from Alamo.",
    "lifeStage": "Leadership",
    "themes": [
      "Career Choices",
      "Community",
      "Financial Responsibility",
      "Gratitude",
      "Identity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 3085,
    "principles": [
      "Make superior client service the organizing priority.",
      "Treat risk management as a central, firm-wide service theme.",
      "Create systems and incentives to overcome provincialism and enable firm-wide expertise sharing.",
      "Use exhaustive preparation and effective communications to alter organizational momentum.",
      "Build internal knowledge management to harness firm resources."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S25",
    "slug": "alamo-rent-a-car",
    "title": "Alamo Rent A Car",
    "summary": "The narrator becomes CEO of Alamo Rent A Car in 1995, implements rapid strategic, operational, financial and cultural changes to turn the company from large losses to profitability, and ultimately sells it to AutoNation. He emphasizes clear agreements, decisive leadership, and rebuilding key relationships.",
    "lifeStage": "Leadership",
    "themes": [
      "Adversity",
      "Career Choices",
      "Curiosity",
      "Financial Responsibility",
      "Gratitude",
      "Leadership"
    ],
    "wordCount": 4476,
    "principles": [
      "Make key agreements explicit in writing to eliminate ambiguity and secure authority.",
      "Move quickly and decisively once priorities are set.",
      "Repair damaged supplier relationships through direct, face-to-face negotiation in neutral settings.",
      "Signal seriousness about strategic priorities by changing leadership when execution stalls.",
      "Invest in data and technology to change industry economics where conventional approaches fail.",
      "Engage front-line employees directly to surface operational problems and improve communication."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S26",
    "slug": "corporate-boards-and-consulting",
    "title": "Corporate Boards and Consulting",
    "summary": "After leaving his executive role in 1997, the narrator built a third career as a corporate board member, consultant and adjunct professor, through a sequence of board appointments, entrepreneurial investments, consulting engagements and teaching. He experienced notable successes (Alliance Data, Fed board, consulting retainers) and failures (Laundromax), and learned governance, risk and professional lessons.",
    "lifeStage": "Leadership",
    "themes": [
      "Adversity",
      "Career Choices",
      "Curiosity",
      "Gratitude",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 3464,
    "principles": [
      "Judge founders and leaders by intelligence, energy and integrity.",
      "Accept that external market forces can make outcomes unmanageable despite sound planning.",
      "Maintain professional conduct when disagreeing or exiting roles.",
      "Use failures as teaching tools and case studies to pass lessons to others.",
      "Leverage personal and professional networks to create opportunities and solutions."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S27",
    "slug": "lessons-on-business-ethics",
    "title": "Lessons on Business Ethics",
    "summary": "A career auditor recounts multiple instances of fraud and ethical breaches encountered over decades, describing investigative actions, escalation choices, and reflections on professional values.",
    "lifeStage": "Leadership",
    "themes": [
      "Career Choices",
      "Gratitude",
      "Identity",
      "Integrity",
      "Work Ethic"
    ],
    "wordCount": 2833,
    "principles": [
      "Maintain professional skepticism and vigilance.",
      "Investigate anomalies thoroughly before concluding.",
      "Escalate material misstatements to appropriate authority when management resists correction.",
      "Value confidentiality when counseling individuals facing sensitive disclosures.",
      "Question the fairness of punitive actions and consider proportionality."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S28",
    "slug": "career-summary",
    "title": "Career Summary",
    "summary": "A former KPMG partner reflects on a long career, gratitude to the firm, and his transition to lead a major company where he swiftly addressed inherited problems and succeeded.",
    "lifeStage": "Reflection",
    "themes": [
      "Adversity",
      "Career Choices",
      "Gratitude",
      "Identity",
      "Integrity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 512,
    "principles": [
      "Acknowledge and be grateful for institutional development and mentorship.",
      "Take ownership of problems you inherit and treat them as yours to solve.",
      "Act decisively and swiftly when circumstances demand urgency.",
      "Leverage broad institutional experience and knowledge when stepping into leadership roles.",
      "Value the career-wide accumulation of experiences and give back via boards, consulting, and teaching."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S29",
    "slug": "what-a-wonderful-world",
    "title": "What a Wonderful World",
    "summary": "A first-person travelogue reflecting on decades of domestic and international travel, arguing that first-hand observation yields deeper understanding than second-hand accounts and recounting diverse travel experiences and a humanitarian trip.",
    "lifeStage": "Reflection",
    "themes": [
      "Career Choices",
      "Community",
      "Gratitude",
      "Identity",
      "Work Ethic"
    ],
    "wordCount": 3598,
    "principles": [
      "First-hand observation provides deeper understanding than reading or media.",
      "Independent, flexible exploration yields more authentic experiences than rigid tours.",
      "Hands-on participation, even if small, is valuable in humanitarian response.",
      "Physical mementos and local craftsmanship connect travelers to places and people."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S30",
    "slug": "famous-people-i-ve-met-none-of-whom-would-ever-remember-me",
    "title": "Famous People I’ve Met (None of Whom Would Ever Remember Me)",
    "summary": "The narrator recounts brief encounters with various famous people across decades and the practical, personal lessons gleaned from those meetings.",
    "lifeStage": "Reflection",
    "themes": [
      "Adversity",
      "Career Choices",
      "Community",
      "Curiosity",
      "Gratitude",
      "Identity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 1992,
    "principles": [
      "Minor setbacks do not derail long-term career momentum.",
      "Serendipity combined with skill can produce transformative opportunities.",
      "Direct engagement with people reduces intimidation and builds confidence.",
      "Observe others' grit and sacrifice as motivation to persist in your ambitions.",
      "Humility and selflessness are powerful leadership virtues regardless of fame.",
      "Family devotion informs leadership priorities and commitment."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S31",
    "slug": "these-are-a-few-of-my-favorite-things",
    "title": "These Are a Few of My Favorite Things",
    "summary": "The narrator recounts how moments of music in a monotonous school setting sparked a lifelong love of music and lists favorite compositions that shaped emotions and memories.",
    "lifeStage": "Reflection",
    "themes": [
      "Curiosity",
      "Gratitude",
      "Integrity"
    ],
    "wordCount": 1901,
    "principles": [
      "Find and acknowledge beauty in mundane settings.",
      "Use music as a tool for emotional regulation and memory triggers.",
      "Preserve meaningful artifacts to maintain connection to formative experiences.",
      "Internalize beloved works by learning and practicing them."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S32",
    "slug": "for-the-love-of-words",
    "title": "For the Love of Words",
    "summary": "A reflective first-person account of a lifelong passion for vocabulary: influences, habits (collections, subscriptions, games), and the pleasure derived from words and their clarity.",
    "lifeStage": "Reflection",
    "themes": [
      "Adversity",
      "Career Choices",
      "Community",
      "Curiosity",
      "Financial Responsibility",
      "Gratitude",
      "Identity",
      "Integrity",
      "Work Ethic"
    ],
    "wordCount": 1100,
    "principles": [
      "Regular, small exposures build vocabulary over time.",
      "Curate a personal, persistent list to deepen familiarity with chosen words.",
      "Learning driven by intrinsic enjoyment sustains long-term practice.",
      "Use playful competition to reinforce learning and maintain engagement.",
      "Sharing work publicly can create durability and useful feedback."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S33",
    "slug": "houses-cars-and-boats",
    "title": "Houses, Cars and Boats",
    "summary": "A personal memoir tracing decades of the narrator's choices about homes, automobiles, and boats, showing how material desires, research, advice, and learning from mistakes shaped family life and investments.",
    "lifeStage": "Reflection",
    "themes": [
      "Career Choices",
      "Community",
      "Curiosity",
      "Financial Responsibility",
      "Gratitude",
      "Identity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 2946,
    "principles": [
      "Learn from financial mistakes and take corrective action.",
      "Do your own research when external advice is vague or inconsistent.",
      "Use major assets (homes, boats) to create family experiences and social value.",
      "Seek trusted counsel before making large expenditures.",
      "Mitigate operational risk by hiring expertise and acquiring skills when entering a new domain."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S34",
    "slug": "my-three-sons",
    "title": "My Three Sons",
    "summary": "A father reflects on raising his three sons, describing their personalities, education, milestones, and the values and choices that shaped their development and families.",
    "lifeStage": "Reflection",
    "themes": [
      "Financial Responsibility"
    ],
    "wordCount": 2260,
    "principles": [
      "Prioritize providing the best possible education for children.",
      "Treat children with respect and as autonomous individuals.",
      "Be consistent in parenting and dealings with children.",
      "Support independence by stepping back when a child requests ownership of a decision.",
      "Act promptly on credible external observations about a child's needs (e.g., teacher concerns)."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S35",
    "slug": "the-gift-of-family",
    "title": "The Gift of Family",
    "summary": "A narrator reflects on family as the bedrock of life, describing children, spouses, grandchildren, and how love and regular contact have sustained close relationships despite geographic distance.",
    "lifeStage": "Reflection",
    "themes": [
      "Career Choices",
      "Family",
      "Financial Responsibility"
    ],
    "wordCount": 1567,
    "principles": [
      "Sustain emotional closeness despite physical distance.",
      "Trust and rely on capable partners to manage family responsibilities during absences.",
      "Expose children to varied environments to build adaptability, independence and confidence.",
      "Use periodic family gatherings and celebrations to reinforce connections.",
      "Leverage modern communication technology to maintain regular contact.",
      "Express gratitude and regard family as a precious gift."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S36",
    "slug": "charles-t-brumfield",
    "title": "Charles T. Brumfield",
    "summary": "A reflection on a fifty-year friendship between the narrator and Charles Brumfield, tracing their college collaboration, long correspondence, pranks, and Brumfield’s adventurous, cosmopolitan life.",
    "lifeStage": "Reflection",
    "themes": [
      "Career Choices",
      "Community",
      "Family",
      "Financial Responsibility"
    ],
    "wordCount": 1945,
    "principles": [
      "Cultivate enduring friendships through mutual respect and shared values.",
      "Leverage complementary strengths within a team: visible leader and steady behind-the-scenes support.",
      "Place trusted people in roles of responsibility.",
      "Respect divergent viewpoints while holding to shared ethical foundations.",
      "Prioritize experience and independence over material accumulation."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S37",
    "slug": "to-god-be-the-glory",
    "title": "To God Be The Glory",
    "summary": "A personal testimony recounting lifelong Christian formation beginning with childhood VBS, a pivotal conversion at age eleven, sustained service in church leadership, exploration of other faiths, and a conviction of stewardship and gratitude.",
    "lifeStage": "Reflection",
    "themes": [
      "Adversity",
      "Community",
      "Financial Responsibility",
      "Identity"
    ],
    "wordCount": 2114,
    "principles": [
      "Spiritual formation is rooted in early, repeated practices and rituals.",
      "Mentorship and pastoral presence can catalyze decisive commitments.",
      "Stewardship entails both time and money as obligations to community and faith.",
      "Active participation in religious programs deepens faith and personal growth.",
      "Gratitude frames lifelong spiritual perspective."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S38",
    "slug": "for-good-for-ever",
    "title": "For Good. For Ever.",
    "summary": "A personal account of lifelong commitment to community service through sustained financial giving, board leadership, volunteer work, and the ethic of \"paying it forward.\"",
    "lifeStage": "Reflection",
    "themes": [
      "Adversity",
      "Career Choices",
      "Community",
      "Curiosity",
      "Financial Responsibility",
      "Gratitude",
      "Identity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 1385,
    "principles": [
      "Sustained, consistent giving builds long-term community impact.",
      "Volunteer leadership roles are opportunities to apply professional skills and to learn leadership.",
      "Combine monetary support with time and leadership for greater impact.",
      "Adopt an ethic of reciprocity—'pay it forward'—as a guiding motive for service."
    ],
    "volume": "P1"
  },
  {
    "storyId": "P1_S39",
    "slug": "moments-to-remember",
    "title": "Moments to Remember",
    "summary": "A memoirist reflects on a series of memorable personal moments across his life—marriage, education, family vacations, births and losses—and describes a late-life turn to retrospection, gratitude, and sense-making.",
    "lifeStage": "Reflection",
    "themes": [
      "Adversity",
      "Career Choices",
      "Gratitude",
      "Identity",
      "Leadership",
      "Work Ethic"
    ],
    "wordCount": 2198,
    "principles": [
      "Acknowledge and be grateful for the support and influence of others.",
      "Maintain consistent goal-setting to drive long-term personal improvement.",
      "Use retrospection in later life to clarify meaning and legacy.",
      "Accept serendipity as a meaningful factor in life outcomes.",
      "Treat major commitments with seriousness and intentionality."
    ],
    "volume": "P1"
  }
];

export const themesData: ThemeCard[] = [
  {
    "slug": "career-choices",
    "name": "Career Choices",
    "storyCount": 31,
    "storyIds": [
      "P1_S01",
      "P1_S02",
      "P1_S03",
      "P1_S04",
      "P1_S05",
      "P1_S07",
      "P1_S08",
      "P1_S09",
      "P1_S10",
      "P1_S11",
      "P1_S12",
      "P1_S13",
      "P1_S16",
      "P1_S17",
      "P1_S18",
      "P1_S19",
      "P1_S20",
      "P1_S23",
      "P1_S24",
      "P1_S25",
      "P1_S26",
      "P1_S27",
      "P1_S28",
      "P1_S29",
      "P1_S30",
      "P1_S32",
      "P1_S33",
      "P1_S35",
      "P1_S36",
      "P1_S38",
      "P1_S39"
    ]
  },
  {
    "slug": "gratitude",
    "name": "Gratitude",
    "storyCount": 26,
    "storyIds": [
      "P1_S01",
      "P1_S02",
      "P1_S03",
      "P1_S04",
      "P1_S05",
      "P1_S08",
      "P1_S10",
      "P1_S11",
      "P1_S12",
      "P1_S17",
      "P1_S18",
      "P1_S19",
      "P1_S20",
      "P1_S23",
      "P1_S24",
      "P1_S25",
      "P1_S26",
      "P1_S27",
      "P1_S28",
      "P1_S29",
      "P1_S30",
      "P1_S31",
      "P1_S32",
      "P1_S33",
      "P1_S38",
      "P1_S39"
    ]
  },
  {
    "slug": "identity",
    "name": "Identity",
    "storyCount": 26,
    "storyIds": [
      "P1_S01",
      "P1_S02",
      "P1_S03",
      "P1_S04",
      "P1_S05",
      "P1_S06",
      "P1_S08",
      "P1_S10",
      "P1_S11",
      "P1_S12",
      "P1_S17",
      "P1_S18",
      "P1_S19",
      "P1_S20",
      "P1_S21",
      "P1_S23",
      "P1_S24",
      "P1_S27",
      "P1_S28",
      "P1_S29",
      "P1_S30",
      "P1_S32",
      "P1_S33",
      "P1_S37",
      "P1_S38",
      "P1_S39"
    ]
  },
  {
    "slug": "work-ethic",
    "name": "Work Ethic",
    "storyCount": 26,
    "storyIds": [
      "P1_S01",
      "P1_S02",
      "P1_S03",
      "P1_S04",
      "P1_S05",
      "P1_S07",
      "P1_S08",
      "P1_S09",
      "P1_S10",
      "P1_S11",
      "P1_S12",
      "P1_S17",
      "P1_S18",
      "P1_S19",
      "P1_S20",
      "P1_S23",
      "P1_S24",
      "P1_S26",
      "P1_S27",
      "P1_S28",
      "P1_S29",
      "P1_S30",
      "P1_S32",
      "P1_S33",
      "P1_S38",
      "P1_S39"
    ]
  },
  {
    "slug": "curiosity",
    "name": "Curiosity",
    "storyCount": 23,
    "storyIds": [
      "P1_S03",
      "P1_S04",
      "P1_S05",
      "P1_S06",
      "P1_S07",
      "P1_S09",
      "P1_S10",
      "P1_S11",
      "P1_S12",
      "P1_S13",
      "P1_S16",
      "P1_S18",
      "P1_S20",
      "P1_S21",
      "P1_S22",
      "P1_S23",
      "P1_S25",
      "P1_S26",
      "P1_S30",
      "P1_S31",
      "P1_S32",
      "P1_S33",
      "P1_S38"
    ]
  },
  {
    "slug": "leadership",
    "name": "Leadership",
    "storyCount": 23,
    "storyIds": [
      "P1_S02",
      "P1_S04",
      "P1_S05",
      "P1_S06",
      "P1_S07",
      "P1_S09",
      "P1_S12",
      "P1_S14",
      "P1_S15",
      "P1_S16",
      "P1_S18",
      "P1_S19",
      "P1_S20",
      "P1_S21",
      "P1_S22",
      "P1_S24",
      "P1_S25",
      "P1_S26",
      "P1_S28",
      "P1_S30",
      "P1_S33",
      "P1_S38",
      "P1_S39"
    ]
  },
  {
    "slug": "financial-responsibility",
    "name": "Financial Responsibility",
    "storyCount": 21,
    "storyIds": [
      "P1_S05",
      "P1_S06",
      "P1_S08",
      "P1_S09",
      "P1_S11",
      "P1_S12",
      "P1_S13",
      "P1_S14",
      "P1_S15",
      "P1_S21",
      "P1_S22",
      "P1_S23",
      "P1_S24",
      "P1_S25",
      "P1_S32",
      "P1_S33",
      "P1_S34",
      "P1_S35",
      "P1_S36",
      "P1_S37",
      "P1_S38"
    ]
  },
  {
    "slug": "community",
    "name": "Community",
    "storyCount": 18,
    "storyIds": [
      "P1_S01",
      "P1_S03",
      "P1_S05",
      "P1_S06",
      "P1_S08",
      "P1_S10",
      "P1_S11",
      "P1_S12",
      "P1_S15",
      "P1_S21",
      "P1_S24",
      "P1_S29",
      "P1_S30",
      "P1_S32",
      "P1_S33",
      "P1_S36",
      "P1_S37",
      "P1_S38"
    ]
  },
  {
    "slug": "adversity",
    "name": "Adversity",
    "storyCount": 16,
    "storyIds": [
      "P1_S02",
      "P1_S05",
      "P1_S06",
      "P1_S07",
      "P1_S09",
      "P1_S15",
      "P1_S20",
      "P1_S21",
      "P1_S25",
      "P1_S26",
      "P1_S28",
      "P1_S30",
      "P1_S32",
      "P1_S37",
      "P1_S38",
      "P1_S39"
    ]
  },
  {
    "slug": "integrity",
    "name": "Integrity",
    "storyCount": 13,
    "storyIds": [
      "P1_S06",
      "P1_S07",
      "P1_S09",
      "P1_S13",
      "P1_S15",
      "P1_S18",
      "P1_S19",
      "P1_S20",
      "P1_S22",
      "P1_S27",
      "P1_S28",
      "P1_S31",
      "P1_S32"
    ]
  },
  {
    "slug": "family",
    "name": "Family",
    "storyCount": 4,
    "storyIds": [
      "P1_S08",
      "P1_S12",
      "P1_S35",
      "P1_S36"
    ]
  },
  {
    "slug": "mentorship",
    "name": "Mentorship",
    "storyCount": 4,
    "storyIds": [
      "P1_S02",
      "P1_S03",
      "P1_S06",
      "P1_S17"
    ]
  }
];

export const timelineData: TimelineEvent[] = [
  {
    "year": 1959,
    "event": "Entered college",
    "organization": "Mississippi Southern College (USM)",
    "location": "Hattiesburg, Mississippi",
    "storyRef": "P1_S36",
    "illustration": "/timeline/usm.jpg"
  },
  {
    "year": 1959,
    "event": "Elected president of Student Government Association",
    "organization": "University of Southern Mississippi",
    "location": "Hattiesburg, Mississippi",
    "storyRef": "P1_S36"
  },
  {
    "year": 1962,
    "event": "Job search and office visits to accounting firms",
    "organization": "USM",
    "location": "New Orleans, Houston, Jackson",
    "storyRef": "P1_S16"
  },
  {
    "year": 1962,
    "event": "Chose Peat Marwick",
    "organization": "",
    "location": "Jackson office (Peat Marwick Mitchell & Co.), Jackson, Mississippi",
    "storyRef": "P1_S16",
    "illustration": "/timeline/accounting-machine.jpg"
  },
  {
    "year": 1963,
    "event": "Graduated from University of Southern Mississippi",
    "organization": "University of Southern Mississippi",
    "location": "Hattiesburg, Mississippi",
    "storyRef": "P1_S17"
  },
  {
    "year": 1963,
    "event": "Married Dot at First Baptist Church",
    "organization": "First Baptist Church",
    "location": "Mississippi",
    "storyRef": "P1_S39"
  },
  {
    "year": 1963,
    "event": "Joined Peat Marwick; first paycheck; United Way payroll deduction began",
    "organization": "Peat Marwick",
    "location": "Jackson, Mississippi",
    "storyRef": "P1_S38",
    "illustration": "/timeline/mississippi-jackson.jpg"
  },
  {
    "year": 1968,
    "event": "First son Paul born",
    "organization": "St. Dominic Hospital",
    "location": "Jackson, Mississippi",
    "storyRef": "P1_S34"
  },
  {
    "year": 1970,
    "event": "Became partner at Peat Marwick",
    "organization": "Peat Marwick",
    "location": "Jackson, Mississippi",
    "storyRef": "P1_S19"
  },
  {
    "year": 1971,
    "event": "Moved to Orlando to establish new Peat Marwick office",
    "organization": "Peat Marwick",
    "location": "Orlando, Florida",
    "storyRef": "P1_S20",
    "illustration": "/timeline/florida-orlando.jpg"
  },
  {
    "year": 1971,
    "event": "Second son John born",
    "organization": "Orange Memorial Hospital",
    "location": "Orlando, Florida",
    "storyRef": "P1_S34"
  },
  {
    "year": 1975,
    "event": "Relocated to Fort Lauderdale as managing partner",
    "organization": "Peat Marwick",
    "location": "Fort Lauderdale, Florida",
    "storyRef": "P1_S21",
    "illustration": "/timeline/florida-fort-lauderdale.jpg"
  },
  {
    "year": 1977,
    "event": "Third son Mark born",
    "organization": "Holy Cross Hospital",
    "location": "Fort Lauderdale, Florida",
    "storyRef": "P1_S34"
  },
  {
    "year": 1989,
    "event": "Asked to move to Baltimore; became managing partner",
    "organization": "KPMG",
    "location": "Baltimore, Maryland",
    "storyRef": "P1_S22",
    "illustration": "/timeline/maryland-baltimore.jpg"
  },
  {
    "year": 1990,
    "event": "Invited to dinner at Governor's mansion",
    "organization": "",
    "location": "Maryland, Annapolis, Maryland",
    "storyRef": "P1_S39",
    "illustration": "/timeline/maryland-annapolis.jpg"
  },
  {
    "year": 1991,
    "event": "Arrived in Philadelphia as managing partner",
    "organization": "KPMG",
    "location": "Philadelphia, Pennsylvania",
    "storyRef": "P1_S23",
    "illustration": "/timeline/pennsylvania-philadelphia.jpg"
  },
  {
    "year": 1993,
    "event": "Traveled to Baltimore for Father Sellinger's funeral",
    "organization": "Loyola University / church",
    "location": "Baltimore, Maryland",
    "storyRef": "P1_S37"
  },
  {
    "year": 1994,
    "event": "Miss Frances Mallory",
    "organization": "teacher) died; home donated to church (First Baptist Church",
    "location": "Calhoun City, Mississippi",
    "storyRef": "P1_S03"
  },
  {
    "year": 1995,
    "event": "Became CEO of Alamo Rent A Car",
    "organization": "Alamo Rent A Car",
    "location": "Fort Lauderdale, Florida",
    "storyRef": "P1_S25",
    "illustration": "/timeline/alamo-cars.jpg"
  },
  {
    "year": 1996,
    "event": "Ordered ten GM experimental electric cars for Alamo rental testing",
    "organization": "Alamo Rent A Car",
    "location": "",
    "storyRef": "P1_S33"
  },
  {
    "year": 1997,
    "event": "Alamo role ended; transition to boards and consulting",
    "organization": "",
    "location": "",
    "storyRef": "P1_S26"
  },
  {
    "year": 1997,
    "event": "Joined board of Federal Reserve Bank of Miami",
    "organization": "Federal Reserve Bank of Miami",
    "location": "Miami, Florida",
    "storyRef": "P1_S26",
    "illustration": "/timeline/florida-miami.jpg"
  },
  {
    "year": 1998,
    "event": "Purchased Mallory House",
    "organization": "teacher's former home",
    "location": "Calhoun City, Mississippi",
    "storyRef": "P1_S03"
  },
  {
    "year": 1999,
    "event": "Joined board of CRA Qualified Investment Fund",
    "organization": "CRA Qualified Investment Fund",
    "location": "South Florida",
    "storyRef": "P1_S26"
  },
  {
    "year": 2000,
    "event": "Laundromax failed; capital markets dried up",
    "organization": "Laundromax",
    "location": "",
    "storyRef": "P1_S26",
    "illustration": "/timeline/laundromat.jpg"
  },
  {
    "year": 2002,
    "event": "Invited to join BankAtlantic Bancorp board",
    "organization": "BankAtlantic Bancorp",
    "location": "Florida",
    "storyRef": "P1_S26",
    "illustration": "/timeline/bankatlantic.jpg"
  },
  {
    "year": 2003,
    "event": "Began teaching as adjunct at Nova Southeastern University",
    "organization": "Nova Southeastern University",
    "location": "Florida",
    "storyRef": "P1_S26",
    "illustration": "/timeline/nova-southeastern.jpg"
  },
  {
    "year": 2012,
    "event": "BankAtlantic sold to BB&T",
    "organization": "BankAtlantic Bancorp",
    "location": "Florida",
    "storyRef": "P1_S26"
  },
  {
    "year": 2012,
    "event": "Grandson Ethan Keith Cobb born",
    "organization": "",
    "location": "",
    "storyRef": "P1_S35"
  },
  {
    "year": 2013,
    "event": "Resigned from BFC Financial / BankAtlantic boards; Oklahoma City tornado cleanup",
    "organization": "",
    "location": "Oklahoma City / Florida",
    "storyRef": "P1_S26"
  },
  {
    "year": 2013,
    "event": "Volunteer cleanup trip to Moore",
    "organization": "",
    "location": "Oklahoma after tornado (Church group), Moore, Oklahoma",
    "storyRef": "P1_S38"
  },
  {
    "year": 2014,
    "event": "Antarctica expedition; rounded out seven continents",
    "organization": "",
    "location": "Antarctica",
    "storyRef": "P1_S29",
    "illustration": "/timeline/antarctica.jpg"
  }
];
