/**
 * generate-static-data.ts
 *
 * Reads wiki files and generates a JSON file that client components
 * can import directly. Run after compile-wiki.ts.
 *
 * Run: npx tsx scripts/generate-static-data.ts
 */

import * as fs from "fs";
import * as path from "path";

const WIKI = path.join(process.cwd(), "content/wiki");
const OUT = path.join(process.cwd(), "src/lib/wiki/static-data.ts");

interface StoryCard {
  storyId: string;
  slug: string;
  title: string;
  summary: string;
  lifeStage: string;
  themes: string[];
  wordCount: number;
  principles: string[];
}

interface ThemeCard {
  slug: string;
  name: string;
  storyCount: number;
  storyIds: string[];
}

interface TimelineEvent {
  year: number;
  event: string;
  organization: string;
  location: string;
  storyRef: string;
  illustration?: string;
}

function extractMetadata(content: string, key: string): string {
  const regex = new RegExp(`\\*\\*${key}:\\*\\*[ \\t]*(.+)`);
  return content.match(regex)?.[1]?.trim() || "";
}

function extractSection(content: string, heading: string): string[] {
  const escapedHeading = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const regex = new RegExp(`## ${escapedHeading}\\n\\n([\\s\\S]*?)(?=\\n## |\\n---|$)`);
  const match = content.match(regex);
  if (!match) return [];
  return match[1]
    .split("\n")
    .filter((l) => l.startsWith("- "))
    .map((l) => l.replace(/^-\s*/, "").trim());
}

function main() {
  // Stories
  const storiesDir = path.join(WIKI, "stories");
  const stories: StoryCard[] = fs
    .readdirSync(storiesDir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => {
      const content = fs.readFileSync(path.join(storiesDir, f), "utf-8");
      const storyIdMatch = content.match(/\*\*Story ID:\*\*\s*(P\d+_S\d+)/);
      if (!storyIdMatch) return null;

      const titleMatch = content.match(/^# (.+)/m);
      const summaryMatch = content.match(/^> (.+)/m);
      const slug = f.replace(/\.md$/, "").replace(/^P\d+_S\d+-/, "");

      return {
        storyId: storyIdMatch[1],
        slug,
        title: titleMatch?.[1] || "",
        summary: summaryMatch?.[1] || "",
        lifeStage: extractMetadata(content, "Life Stage"),
        themes: extractMetadata(content, "Themes").split(",").map((t) => t.trim()).filter(Boolean),
        wordCount: parseInt(extractMetadata(content, "Word Count")) || 0,
        principles: extractSection(content, "What This Story Shows"),
        volume: storyIdMatch[1].match(/^(P\d+)/)?.[1] || "P1",
      };
    })
    .filter(Boolean)
    .sort((a, b) => a!.storyId.localeCompare(b!.storyId)) as StoryCard[];

  // Themes
  const themesDir = path.join(WIKI, "themes");
  const themes: ThemeCard[] = fs
    .readdirSync(themesDir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => {
      const content = fs.readFileSync(path.join(themesDir, f), "utf-8");
      const titleMatch = content.match(/^# (.+)/m);
      const countMatch = content.match(/\*\*(\d+) stories\*\*/);
      const slug = f.replace(/\.md$/, "");

      const storiesSection = extractSection(content, "Stories");
      const storyIds = storiesSection
        .map((l) => l.match(/\[\[(P\d+_S\d+)\]\]/)?.[1])
        .filter(Boolean) as string[];

      return {
        slug,
        name: titleMatch?.[1] || slug,
        storyCount: parseInt(countMatch?.[1] || "0") || storyIds.length,
        storyIds,
      };
    })
    .sort((a, b) => b.storyCount - a.storyCount);

  // Timeline
  const timelineContent = fs.readFileSync(path.join(WIKI, "timeline/career-timeline.md"), "utf-8");
  const timelineEvents: TimelineEvent[] = [];
  for (const line of timelineContent.split("\n")) {
    const match = line.match(
      /- \*\*(\d{4})\*\* — (.+?)(?:\s*\((.+?)\))?(?:,\s*(.+?))?\s*—\s*\[\[(P\d+_S\d+)\]\]\s*(?:\|\s*(.+))?/
    );
    if (match) {
      timelineEvents.push({
        year: parseInt(match[1]),
        event: match[2].trim(),
        organization: match[3] || "",
        location: match[4]?.trim() || "",
        storyRef: match[5],
        illustration: match[6]?.trim() || undefined,
      });
    }
  }

  // Write static data module
  const output = `// Auto-generated by scripts/generate-static-data.ts
// Do not edit manually. Run: npx tsx scripts/generate-static-data.ts

export interface StoryCard {
  storyId: string;
  slug: string;
  title: string;
  summary: string;
  lifeStage: string;
  themes: string[];
  wordCount: number;
  principles: string[];
  volume?: string;
}

export interface ThemeCard {
  slug: string;
  name: string;
  storyCount: number;
  storyIds: string[];
}

export interface TimelineEvent {
  year: number;
  event: string;
  organization: string;
  location: string;
  storyRef: string;
  illustration?: string;
}

export const storiesData: StoryCard[] = ${JSON.stringify(stories, null, 2)};

export const themesData: ThemeCard[] = ${JSON.stringify(themes, null, 2)};

export const timelineData: TimelineEvent[] = ${JSON.stringify(timelineEvents, null, 2)};
`;

  fs.writeFileSync(OUT, output);
  console.log(`✅ Static data generated → ${OUT}`);
  console.log(`   ${stories.length} stories, ${themes.length} themes, ${timelineEvents.length} timeline events`);
}

main();
